[package]
name = "asymptote"
version = "0.4.2"
authors = ["Maximilian Lupke <maxlupke@gmail.com>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
rand = "0.5.0"

[profile.release]
lto = true
debug = true
codegen-units = 1

[features]
tune = []
