[package]
name = "asymptote"
version = "0.2.0"
authors = ["Maximilian Lupke <maxlupke@gmail.com>"]
license = "GPL-3.0-only"

[dependencies]
rand = "0.5.0"
lazy_static = "1.0.1"

[profile.release]
debug = true
