[package]
name = "asymptote"
version = "0.4.0"
authors = ["Maximilian Lupke <maxlupke@gmail.com>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]
rand = "0.5.0"
lazy_static = "1.0.1"

[profile.release]
debug = true
codegen-units = 1
